language: python
python:
  - "3.6"
  # - "3.7"
install:
  # cython
  # - pip install cython -vvv
  # ODE
  # - ./install_ode.sh
  # py3ode
  - pip install .
script: pytest
deploy:
  provider: pypi
  user: filipeabperes
  password:
    secure: "hVtAPyYTgPDG6EYRKcbKHs8zi/7JJH+xElz0Iktgn/TS/bMnDmhoiZKBN0NNrX+SNX5CowaCzyXCQhxF9E6Ddjgc7XUQaMtHblg9A2RZlLdyTrrnWWvR38WbsXN3TEn5RanYRvX1x916ZWfgA1ujZVGvuKcRcMlYP2FK835WEjpiiNLf+KQKP7pjXlA4oXjTdB07vFlM23Z/VyZAJLQtaOv93hJ47SOG4NuqdcfbRtkeJbqBbG1UMMCv/3b0/ia+T4t83dNTj2Ku1IlzpVYNh27Vn+IClhyESFYjOhr1HTDSF/EadWf1C1ZZzbO4nGgtCCm+MvZVVN8ZYmenPyFDsrrjfMx9u8krhgFJLrGng4Zpj1Chc/YXdNaI56SA0An+ehwNc2ezhYlI2MlADN/ndayVXsnJg3mBJOHMu7uo0SQsEDS8wCFL3RXxlZJ/lFMwHLyxjut2MoMjegGBCfNVTs2n8s7pEdn09Xi+7CsIgWrySUOQhQ3DcAe60ADojGtj/mR3hYaxIAvf0m7TKcufy3WyuQm2g9et7vyVJ+/7+0sAMnMGZItz8cfWl55zazJkSpwPCWKn16uXIN7aoTCd8O4krJQYfdpc1FsA4kT7AL1ZsBP6M6w2F1yDXVW9lSouCe2JLps8jAltlT9NVmvcbXa5V9WjA/3szI3upCKZAOM="
  on:
    distributions: sdist
    repo: filipeabperes/Py3ODE
